/*
 ============================================================================
 Name        : problem_29.c
 Author      : Cao Liang
 Version     :
 Copyright   : Anyone can use it for anything
 Description : Hello World in C, Ansi-style


 Consider all integer combinations of ab for 2  a  5 and 2  b  5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?
 ============================================================================
 */

#include <stdio.h>
#include <stdlib.h>

#define TERM_SIZE 100

void calculate(void)
{
	int i, j, total_count = 0, temp_count = 0;
	for (i = 2; i <= TERM_SIZE; i++)
	{
		temp_count = 0;
		for (j = 2; j < i; j++)
		{
			if (i == j * j)
			{
				temp_count = TERM_SIZE / 2 + TERM_SIZE % 2;
				break;
			}
		}

		if (temp_count)
			total_count += temp_count;
		else
			total_count += TERM_SIZE - 1;
	}

	printf("total_count:%d\n", total_count);
}


int main(void) {
	puts("Hello World"); /* prints Hello World */
	calculate();
	return EXIT_SUCCESS;
}
